### ISSUE TITLE
auro-alert: blueprint

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-alert#20]
# Blueprint
We need a blueprint for auro-alert that matches the features we have currently on our doc site.

## Outline tasks

- [ ] anatomy
- [ ] color
- [ ] typography
- [ ] layout
- [ ] spacing
- [ ] animation/behavior
- [ ] variants
- [ ] states (hover, focus, active, focus-visible)
- [ ] a11y

## Optional

- [ ] Competitive analysis
- [ ] research
- [ ] site audit
- [ ] usage audit
- [ ] inspirational work
# Publish New Component

## Specific steps required to publish this component.

1. __Design & Planning__
    - [ ] Blueprint is created
1. __Development__
    - [ ] Sync with devs and get feedback and to make sure features in the blueprint match what will be developed in the first milestone.
    - [ ] Archive any features that will need to be part of a future version.
1. __Documentation__
      - [ ] Component properly described
      - [ ] Component use case(s) outlined
      - [ ] `Do Not` section outlines implementation scenarios to avoid
      - Example Section
        - [ ] Basic example of simplest use case
        - [ ] Work with dev to add other common use cases
        - [ ] Add figma instructions
        - [ ] Create release notes for new component
        - [ ] Add Figma tab and figma examples

1. __Publishing__
    - [ ] Publish component to figma library
    - [ ] Create PR for release on doc site

**Comment by leeejune** [comment]
Blueprint completed: https://www.figma.com/file/E8q4a8izcNeBwZv6gQmmtc/Alert?node-id=322%3A298

**Comment by blackfalcon** [comment]
This is GREAT! Ship it! :shipit:

**Comment by leeejune** [comment]
Released on Figma, will add design notes on the doc site.
