### ISSUE TITLE
auro-alert: padding options

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-alert#28]
## Is your feature request related to a problem? Please describe.

We recently created an advisory page using the auro-alert component.  The padding on the alert with this much content is very tight and doesn't look as nice as the auro-alert with just a single line of text.

## Current Experience

![image](https://user-images.githubusercontent.com/5118118/192640314-d399f910-f6e0-46f9-8d02-219e0ee75283.png)

## Describe the solution you'd like

Give the implementers more options to handle padding depending on the type of content in the alert.  In this case I added 2rem

![image](https://user-images.githubusercontent.com/5118118/192640388-5178ab5c-4615-4f1b-a292-8b341075b656.png)

## Describe alternatives you've considered

Do nothing

## Additional context

Seems to be related to the default auro-header being nice and airy at the top but when used in this context the rest of the content feels very tight.

**Comment by blackfalcon** [comment]
Moving this issue to tech refinement. This could be as simple as exposing CSS parts in the API and allowing the developers to adjust this as needed. 

Documentation should speak to using spacing tokens to reduce the randomness of the padding. 

Overly dictating options like this in the element's API have proven to do more harm than good in the past.
