### ISSUE TITLE
[Github Template] NPM Version Invalid

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/auro-alert#40]
### Please verify the version of auro-alert you have installed

N/A

### Please describe the bug

The NPM version tag in the issue template is invalid:

<img width="250" alt="image" src="https://github.com/AlaskaAirlines/auro-alert/assets/7005799/dadd1ccb-b920-4902-89a9-d86595751094">

### Reproducing the error

This issue cannot be reproduced on the Auro docsite

**Comment by blackfalcon** [comment]
corrected https://github.com/AlaskaAirlines/auro-alert/commit/43443793dfa846f8e32568a3f4b972712d45615c
