### ISSUE TITLE
auro-alert: ability to set background color

### ISSUE THREAD

**Issue by erikalanghauser** [AlaskaAirlines/auro-alert#43]
### Is your feature request related to a problem? Please describe.

Currently, the auro-alerts all have transparent backgrounds. We would like the ability to set the background to white as we have some pages using a neutral background rather than background-lightest.

### Describe the solution you'd like

Ability for engineers to change the background from transparent to white/background-lightest.

### Additional context

![image](https://github.com/AlaskaAirlines/auro-alert/assets/34354487/428c5803-fc20-4478-bb04-2c01e08ebbd6)

Here we see the alert with transparent background which takes on the page's neutral background. Ideally we want to set it to a white background.

**Comment by jordanjones243** [comment]
I have reviewed this issue and have determined that this is NOT a valid bug. By default, `auro-alert` has a transparent background with no specific styles being applied to it. The way to change the background of the alert is to access the shadowDOM specifically through cssParts. In this case, you need to access the `part="alert"` `div` within the shadowDOM.

If you have any questions on how to do so, please reach out to me via Teams.

The highlighted section in this photo is what needs to be targeted to change the background color.

<img width="452" alt="Screen Shot 2023-10-16 at 10 23 19 AM" src="https://github.com/AlaskaAirlines/auro-alert/assets/55807669/4a44007e-189c-4331-aea9-a398b295b895">

**Comment by braven112** [comment]
We are also going to review this with the designers to see if we can provide a standard way to support auro-alert when used on any of our default backgrounds so CSS parts aren't required, but that is a good workaround for today.

**Comment by braven112** [comment]
The decision was made to change the default background from transparent to `--ds-color-background-lightest` or potentially a new token that works with dark mode themes.
