### ISSUE TITLE
Auro Alert icon is not properly styled

### ISSUE THREAD

**Issue by jessieiswise** [AlaskaAirlines/auro-alert#69]
### Please verify the version of auro-alert you have installed

v3.0.2

### Please describe the bug

1 Install auro alert 3.0.2 in a vue app
2 add Auro-alert to component
3 Observe the icon is incorrectly sized
![Screenshot 2024-10-10 at 10 50 32 AM](https://github.com/user-attachments/assets/6b5f6e49-cce8-430a-a377-aafb42c02cd8)

### Reproducing the error

None

### Expected behavior

Properly sized icon

### Additional context

When digging into this, I found that the culprit was this css rule: 
![Screenshot 2024-10-10 at 10 55 18 AM](https://github.com/user-attachments/assets/af513e5d-f800-4be4-bd06-9d489c138fb9)

Note in the Auro demo page, the css rule looks like this:
![Screenshot 2024-10-10 at 10 55 59 AM](https://github.com/user-attachments/assets/c2ff8880-1627-4d5c-affb-08603801a4af)

If I fix the rule in the demo page so that it is actually applied, the same bug appears. I think this may be visible on the vue app due to how it is rendered

![Screenshot 2024-10-10 at 10 57 28 AM](https://github.com/user-attachments/assets/c57f4d40-e05d-4079-9aea-626e1d751249)
![Screenshot 2024-10-10 at 10 59 49 AM](https://github.com/user-attachments/assets/af6f25f8-1cb6-4aee-9b66-7c22a07caea8)

**Comment by blackfalcon** [comment]
I came across this as well and came to a similar conclusion. Why the CSS is presenting itself this way is really weird. 

Additionally, I do not understand why the `customSize` attribute is added to this by default. That attribute is only to be applied when a different constraint is added to the outer parent of the icon. Even with this code corrected, without a parent constraint on the size, you get the same large icon result. 

<img width="1760" alt="Screenshot 2024-10-17 at 2 46 55 PM" src="https://github.com/user-attachments/assets/72ce9d13-c35d-415b-89b5-dbcc8ce92036">
